repository: https://github.com/baloise-incubator/cluster-config.git
#argocdNamespace: "argocd"
#server: "https://kubernetes.default.svc"
namespace:
  annotations: {}
  labels: {}

enableDefaultNetworkPolicy: false
enableDefaultLimitRange: true

roleBindings:
#  - groupName: "team1"
#    clusterRoleName: "admin"

clusterResourceWhitelist:
  - group: '*'
    kind: '*'

namespaceResourceBlacklist:
#  - group: 'apps'
#    kind: 'DaemonSet'

applications:
   argocd:
   sealed-secrets:
   chartmuseum:
